services:
  - type: web
    name: koech-frames-app
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_ANON_KEY
        sync: false
      - key: VITE_DIRECTUS_URL
        sync: false
    domains:
      - frames.koechlabs.com
    healthCheck:
      path: /
      delaySeconds: 30
    autoDeploy: true
    branch: main 